### ISSUE TITLE
Formwrapper cannot fill Checkbox

### ISSUE THREAD

**Issue by 73VW** [chinapandaman/PyPDFForm#558] opened 2024-04-08 15:47 UTC
Hello there,

It seems like the FormWrapper cannot fill checkbox.

Sample code to test with the [sample pdf](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/sample_template.pdf):

```
from PyPDFForm import FormWrapper

filled = FormWrapper("sample_template.pdf").fill(
    {
        "check": True,
    },
    flatten=False
)

with open("output.pdf", "wb+") as output:
    output.write(filled.read())
```

First checkbox stays unchecked.

**Comment by chinapandaman** [comment] 2024-04-09 21:54
Hello, first of all thanks for contributing!

Before we get into the actual coding part, I'm not sure if this issue is reproducible:

1) On my Ubuntu 22.04 LTS machine, I spun up a new virtual environment, deleted all pip caches, ran `pip install -U PyPDFForm`, downloaded the template you linked, and ran the snippet your posted in the thread. And [this](https://github.com/chinapandaman/PyPDFForm/files/14924125/output.pdf) is the generated output. I opened it in both **Chrome** and **Document Viewer** and in both cases the first checkbox **are** checked.
2) There are test cases for `FormWrapper`, for example [this one](https://github.com/chinapandaman/PyPDFForm/blob/master/tests/test_functional_simple.py#L8). And there are also expected PDFs that are used to help asserting these test cases. For the test case I just linked [this](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/simple/sample_filled.pdf) is its expected PDF and you can see the checkboxes that are meant to be checked are both checked. So if `FormWrapper` fails to check appropriate checkboxes these tests will fail, which they don't as of now.
3) I wonder if you are using a PDF browser I have never seen? Different PDF browsers display PDF forms differently. For example the expected PDF I linked in 2), GitHub won't display texts that are put into the text fields. But if you download the PDF and open it in Chrome Chrome will display the texts correctly. If you speculate this might be the issue I suggest you `flatten` the PDF when you fill it and usually flattening will generate consistent results across different PDF browsers.

**Comment by 73VW** [comment] 2024-04-10 05:28
Hello @chinapandaman,

I am using Adobe Acrobat reader to display the pdf. This seems weird that it would work on Chrome but not with Acrobat. Maybe that Acrobat is more severe regarding pdf structure than Chrome?
I will make a fresh install and try to reproduce the issue and attach a screenshot.

**Comment by chinapandaman** [comment] 2024-04-10 21:40
Hmm interesting OK. I mean I don't have Acrobat on my current machine but I believe you. Plus the changes you are making are minor.

So here are some next steps:

1) I created a [new branch](https://github.com/chinapandaman/PyPDFForm/tree/PPF-558) and would love you to first close [your PR](https://github.com/chinapandaman/PyPDFForm/pull/559) and re-open it so that it targets this new branch instead of master.
2) I will then have to do some chores on the new branch to cleanup your changes a bit, as well as adding test cases for these new changes.
3) Once I'm done with that, I will create a new PR from the new branch to master and tag you as a reviewer. I would also love you to verify couple newly generated test case PDFs for me on Acrobat that with the new changes their checkboxes are indeed checked.
4) Once confirmed, I will merge the PR and bump a new release out.

Let me know if you have any question regarding the above.

**Comment by chinapandaman** [comment] 2024-04-12 00:57
Actually nvm about what I said above. I will just put up a PR in that branch.

**Comment by chinapandaman** [comment] 2024-04-12 01:27
Hey, so I migrated your changes into https://github.com/chinapandaman/PyPDFForm/pull/564 with some cleanups. Feel free to go give it a review before I move further with it.

I also updated old tests with the changes. Could you verify that for example [this PDF](https://github.com/chinapandaman/PyPDFForm/blob/PPF-558/pdf_samples/simple/sample_filled.pdf) now has checkbox checked when opened in Adobe Acrobat?

**Comment by 73VW** [comment] 2024-04-12 05:48
Hey buddy!

So I've a made a few tests, starting back with a fresh install in a new venv. I am using python3.11. Your package has been installed through pip and its version is 1.4.17.
I've also re-downloaded the [sample pdf](https://github.com/chinapandaman/PyPDFForm/raw/master/pdf_samples/sample_template.pdf) and the [prescription pdf](https://www.liguepulmonaire.ch/sites/default/files/documents/verordnungsformular_4f.pdf).

Using this code:
``` py
from PyPDFForm import FormWrapper

filled = FormWrapper("sample_template.pdf").fill(
    {
        "test": "Test 1",
        "check": True,
    },
)

with open("output.pdf", "wb+") as output:
    output.write(filled.read())

filled = FormWrapper("verordnungsformular_4f.pdf").fill(
    {
        "LiMA": True,
        "NomPrénom 1": "73VW"
    },
)

with open("output2.pdf", "wb+") as output:
    output.write(filled.read())
```

In Acrobat reader, here's the sample pdf without modifications:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/8bff4d68-e6b5-4b06-8da1-e9818caf6760)

After filling it with the non-patched version of your package:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/f848426b-89a4-4603-a7f4-b05891db4e8c)

It seems that now the checkbox is working but not the text field. I don't understand what's going on here.

Opening the same document in a chromium based browser seem to work:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/52bbc0ea-c511-460b-ada2-648d7826c466)

Testing the same with the prescription form:

No modifications, Acrobat:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/b9aefad2-fcca-4790-a1da-54d027ff74d5)

After filling it, Acrobat:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/f7e77747-4ae6-40af-b2c0-c000fb083830)

After filling it, Chromium:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/d5cd8e51-34b6-46ba-b35d-f49bf773d6cd)


I can't reproduce the bug with the checkboxes but now it happens with the text boxes. Could this be a problem in acrobat? I don't really know. I can't remember updating it this week so this might not be related to it.

Feel free to close this issue as this might not be a problem anymore. If you wish, I can open a new one regarding the text fields.

Sorry for the inconvenience.
Best

**Comment by 73VW** [comment] 2024-04-12 05:51
I've downloaded your sample filled and here's the result:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/ec5548c6-61d5-4066-b6fc-059cede8fd44)

However, it seems that the value is present, just not shown. If I click in the field, I get this:

![image](https://github.com/chinapandaman/PyPDFForm/assets/24651698/7477928a-cf47-492b-94c6-392a3b9508ba)

I've crossed checked the two pdfs in my last comment and it looks the same. If I click in the field, value appears!

**Comment by chinapandaman** [comment] 2024-04-12 22:24
So a bit more about the text not showing up unless clicked issue. This is actually less surprising than checkbox not showing up. If you take a look at how GitHub displays say [this PDF](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/simple/sample_filled.pdf) you will see that texts don't show up there either.

To add a bit more context, when I initially started writing this library, it worked similar to how `FormWrapper` works nowadays. See here: https://github.com/chinapandaman/PyPDFForm/blob/v0.0.1/PyPDFForm/pdf.py#L81

And the reason why what is now `PdfWrapper` eventually took precedence was because the same behavior on the text field, where the text that got filled won't show up unless clicked, existed back then. Except it affected many other PDF viewers, including Chrome and Document Viewer (the default PDF app on Ubuntu). Ultimately this behavior across all PDF viewers was what made me decided to deprecate what is now `FormWrapper` and moved forward with `PdfWrapper`.

So you may ask, why is `FormWrapper` back now? Well recently I was enlightened by a Reddit user. His code snippet for filling PDF forms in place will result in PDFs without the weird text behavior, at least when opened through Chrome and Document Viewer. In the end we found out the magic was [this line](https://github.com/chinapandaman/PyPDFForm/blob/master/PyPDFForm/patterns.py#L124). The `/AP` key, when set with the text that's set to the `/V` key, will render the text fields correctly. I thought I found the silver bullet for this issue, and only [recently](https://github.com/chinapandaman/PyPDFForm/releases/tag/v1.4.13) brought back `FormWrapper`.

So enough history lessons. Here are some next steps:
1) I will still be merging https://github.com/chinapandaman/PyPDFForm/pull/564. I know based on your most recent tests the checkboxes aren't broken even without this patch. But since you did initially observe this, adding on top of that the changes don't break any existing test cases, I think it won't hurt to merge it.
2) I will close this thread as well as [your PR](https://github.com/chinapandaman/PyPDFForm/pull/559). After reading what I said above if you are still interested in discussing the text field issue let's open another thread.

**Closed** 2024-04-12 22:26 UTC
